# Generated by Django 6.0.6 on 2026-08-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
