services:
  - type: web
    name: budgetbuddy-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn budgetbuddy.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: EMAIL_HOST
        value: "smtp-relay.brevo.com"
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USE_SSL
        value: "True"
      - key: EMAIL_USE_TLS
        value: "False"
      - key: EMAIL_HOST_USER
        value: "b6e56d001@smtp-brevo.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "BudgetBuddy <spoortiyadavcspoorthi@gmail.com>"

