# Generated by Django 6.0.6 on 2026-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_budget_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='triggered_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
